Q. What is NUMPY ?

Q. Difference between Numpy and python lists ?

Q. Explain the concept of Broadcasting ?

Q. explain the concept of Masked array in Python ?

Q. How to create numpy array from python list ?

Q. Give different methods to generate random numbers in python ?

-- NumPy (Numerical Python) is a fundamental library in Python for numerical computations. It’s a versatile tool primarily used for its advanced multi-dimensional array support.

Key Features are-

Task-Specific Modules: NumPy offers a rich suite of mathematical functions in areas such as linear algebra, Fourier analysis, and random number generation.

Performance and Speed:
Enables vectorized operations.
Many of its core functions are implemented in C for optimized performance.
It uses contiguous blocks of memory, providing efficient caching and reducing overhead during processing.

Broadcasting: NumPy allows combining arrays of different shapes during arithmetic operations, facilitating streamlined computation.

Linear Algebra: It provides essential linear algebra operations, including matrix multiplication and decomposition methods.

-- NumPy Arrays are Homogeneous (One Data Type)

Every element must have the same data type (all ints, all floats, etc.)
Python lists can contain mixed types (int, str, float, object).

-NumPy Arrays are Fast and Memory Efficient
because NumPy arrays store data in contiguous memory blocks, making operations much faster.
Python lists store references to objects, so they
take more memory
are slower in mathematical operations

-NumPy Supports Vectorized Operations
You can apply mathematical operations to an entire array without loops.

-- Broadcasting means NumPy automatically expands the smaller array so that element-wise operations can be performed with the larger array.This expansion is virtual and no extra memory is used.

Reasons to use Broadcating technique -
To perform vectorized operations efficiently
also to avoid writing loops
and to handle operations between mismatched shapes

To broadcast two arrays:

Rule 1: Compare shapes from right to left

Two dimensions are compatible when:
They are equal OR
One of them is 1

Rule 2: If needed, expand the dimension with size 1

In [2]:
# exmaple 1 of Broadcasting
import numpy as np
a = np.array([1, 2, 3])
b = 10
print(a + b)

# example 2 of Broadcasting
a = np.array([[1],
              [2],
              [3]])   # shape (3, 1)

b = np.array([10, 20, 30])   # shape (3,) => (1, 3)
print(a + b)



[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [3]:
# example 3 of Broadcasting
a = np.array([1, 2, 3])      # shape (3,)
b = np.array([1, 2])         # shape (2,)

print(a + b)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

-- A masked array is a normal NumPy array with an additional mask that indicates which elements should be ignored.

created using:
import numpy.ma as ma

A mask is a boolean array:

True → value is masked (ignored)

False → value is valid (used in computation)

Masked arrays are useful when:

Data has missing values

Some values are invalid or outliers

You want to compute mean, sum, etc., excluding specific elements

In [ ]:
# example of masked array
import numpy as np
import numpy.ma as ma

data = np.array([10, 20, -999, 40])
mask = [False, False, True, False]

m = ma.masked_array(data, mask=mask)
print(m)


In [ ]:
# Creating a NumPy Array from a Python List
import numpy as np

# Regular Python list
py_list = [1, 2, 3, 4, 5]

# Convert to NumPy array
np_array = np.array(py_list)

print(np_array)
print(type(np_array))


-- np.random.rand()
Theory: Generates random floating-point numbers from a uniform distribution in the range [0, 1).
Syntax: np.random.rand(d0, d1, ...)

np.random.randint()
Theory: Generates random integers from a specified range [low, high).
Syntax: np.random.randint(low, high, size)

np.random.normal()
Theory: Generates random numbers from a normal (Gaussian) distribution.
Syntax: np.random.normal(loc, scale, size)

np.random.binomial()
Theory: Generates random numbers from a binomial distribution with n trials and p probability.
Syntax: np.random.binomial(n, p, size)

Theory: Generates random values from a Poisson distribution with a given rate (λ).
Syntax: np.random.poisson(lam, size)

In [4]:
# how to generate random numbers in numpy
np.random.rand(3)
np.random.randint(1, 10, size=5)
np.random.normal(50, 10, size=4)
np.random.binomial(10, 0.5, size=5)
np.random.poisson(4, size=6)


array([7, 2, 2, 4, 8, 5])