In [ ]:
# 1
# how to create a single dimensional array
# how to create a multi dimensional array
# how to return the dimensions of an array as tuple (rows,columns)
# how to return total number of elements in an array
# how to return the datatype of an array



In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

b = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(b)

print(a.shape)
print(b.shape)

print(a.size)
print(b.size)

print(a.dtype)
print(b.dtype)


[1 2 3]
[[1 2 3]
 [3 4 5]
 [6 7 8]]
(3,)
(3, 3)
3
9
int64
int64


In [ ]:
# 2
# to change the shape of your array into desired shape, use reshape() function
# copying the array
# how to sort the array


In [ ]:
a = np.array([1,2,3,4,5,6])
new_a = a.reshape(2,3)
print(new_a)

copied_a = np.copy(a)
print(copied_a)

sorted_a = np.sort(a)
print(sorted_a)



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 5 6]


How to perform each given arithmetic operations using numpy
1. adition
2. subtraction
3. multiplication
4. division
5. modulus
6. power
7. square root
8. sum of all elements in the array
9. finding the minimum in the array
10. finding the maximum in the array
11. calculating the mean of an array
12. calculating the median of an array
13. calculating the standard deviation of values in the array
14. calculating the variance of values in the array
15. calculating the correlation coefficient of the array
16. how to find the index of the minimum array element
17. how to find the index of the maximum array element
18. how to  return the indices of elements in the array that satisfy the given condition.

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 6, 8, 10])

# 1. Addition
addition = np.add(a, b)

# 2. Subtraction
subtraction = np.subtract(a, b)

# 3. Multiplication
multiplication = np.multiply(a, b)

# 4. Division
division = np.divide(a, b)

# 5. Modulus
modulus = np.mod(a, b)

# 6. Power
power = np.power(a, b)

# 7. Square Root
square_root = np.sqrt(a)

# 8. Sum of all elements
sum_all = np.sum(a)

# 9. Minimum value
minimum = np.min(a)

# 10. Maximum value
maximum = np.max(a)

# 11. Mean
mean = np.mean(a)

# 12. Median
median = np.median(a)

# 13. Standard Deviation
std_dev = np.std(a)

# 14. Variance
variance = np.var(a)

# 15. Correlation Coefficient
correlation = np.corrcoef(a, b)

# 16. Index of minimum element
index_min = np.argmin(a)

# 17. Index of maximum element
index_max = np.argmax(a)

# 18. Indices of elements satisfying condition (example: > 25)
indices_condition = np.where(a > 25)

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Modulus:", modulus)
print("Power:", power)
print("Square Root:", square_root)
print("Sum:", sum_all)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
print("Correlation Coefficient:\n", correlation)
print("Index of Minimum:", index_min)
print("Index of Maximum:", index_max)
print("Indices > 25:", indices_condition)


CONCATENATION OF ARRAYS
1. np.concatenate()
2. np.stack()
3. np.hstack()
4. np.vstack()

In [ ]:
import numpy as np

# Sample arrays
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# -------------------------------------
# 1. np.concatenate()  (join along an axis)
# -------------------------------------
concat_axis0 = np.concatenate((a, b), axis=0)  # row-wise (vertical)
concat_axis1 = np.concatenate((a, b), axis=1)  # column-wise (horizontal)

# -------------------------------------
# 2. np.stack()  (adds a new dimension)
# -------------------------------------
stack_axis0 = np.stack((a, b), axis=0)  # new 0th axis
stack_axis1 = np.stack((a, b), axis=1)  # new 1st axis
stack_axis2 = np.stack((a, b), axis=2)  # new 2nd axis

# -------------------------------------
# 3. np.hstack()  (horizontal stacking)
# -------------------------------------
hstack_result = np.hstack((a, b))

# -------------------------------------
# 4. np.vstack()  (vertical stacking)
# -------------------------------------
vstack_result = np.vstack((a, b))


print("----- np.concatenate() -----")
print("Axis 0 (vertical):\n", concat_axis0)
print("Axis 1 (horizontal):\n", concat_axis1)

print("\n----- np.stack() -----")
print("Stack axis 0:\n", stack_axis0)
print("Stack axis 1:\n", stack_axis1)
print("Stack axis 2:\n", stack_axis2)

print("\n----- np.hstack() -----")
print(hstack_result)

print("\n----- np.vstack() -----")
print(vstack_result)


SLICING IN NUMPY ARRAY

1. Basic slicing
2. Slice with step
3. 2D slicing
4. 3D slicing
5. Slicing using :
6. Negative slicing
7. Boolean slicing
8. Fancy slicing (index arrays)
9. Slicing rows
10. Slicing columns
11. Slicing every nth element
12. Slicing ranges in matrices

In [ ]:
import numpy as np

# Sample 1D, 2D, and 3D arrays
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9,10,11,12]])
arr3 = np.arange(24).reshape(2, 3, 4)

# ---------------------------------------------------------
# 1. BASIC 1D SLICING
# ---------------------------------------------------------
slice_1 = arr1[1:5]      # elements from index 1 to 4
slice_2 = arr1[:4]       # from start to index 3
slice_3 = arr1[3:]       # from index 3 to end

# ---------------------------------------------------------
# 2. SLICING WITH STEP
# ---------------------------------------------------------
slice_step = arr1[0:7:2]   # every 2nd element from start to end
slice_reverse = arr1[::-1] # reverse array

# ---------------------------------------------------------
# 3. 2D SLICING
# ---------------------------------------------------------
row_0 = arr2[0, :]       # entire row 0
col_1 = arr2[:, 1]       # entire column 1
submatrix = arr2[0:2, 1:3]  # block slice

# ---------------------------------------------------------
# 4. SLICING WITH NEGATIVE INDICES
# ---------------------------------------------------------
slice_neg = arr1[-5:-1]   # slice using negative positions

# ---------------------------------------------------------
# 5. BOOLEAN SLICING
# ---------------------------------------------------------
bool_slice = arr1[arr1 > 35]  # elements greater than 35

# ---------------------------------------------------------
# 6. FANCY SLICING (INDEX LISTS)
# ---------------------------------------------------------
index_slice = arr1[[0, 2, 5]]   # pick specific positions

# ---------------------------------------------------------
# 7. SLICING ROWS FROM 2D ARRAY
# ---------------------------------------------------------
rows_0_2 = arr2[[0, 2], :]   # rows 0 and 2

# ---------------------------------------------------------
# 8. SLICING COLUMNS FROM 2D ARRAY
# ---------------------------------------------------------
cols_1_3 = arr2[:, [1, 3]]  # columns 1 and 3

# ---------------------------------------------------------
# 9. EVERY Nth ELEMENT IN 2D MATRIX
# ---------------------------------------------------------
every_2_cols = arr2[:, ::2]
every_2_rows = arr2[::2, :]

# ---------------------------------------------------------
# 10. MIXED INDEXING + SLICING
# ---------------------------------------------------------
mix_slice = arr2[1, 1:]    # row 1, columns 1 to end


print("1D Slicing:", slice_1)
print("1D Slicing (start):", slice_2)
print("1D Slicing (end):", slice_3)
print("Step Slicing:", slice_step)
print("Reverse:", slice_reverse)
print("\nRow 0:", row_0)
print("Col 1:", col_1)
print("Submatrix:\n", submatrix)
print("\nNegative slice:", slice_neg)
print("Boolean slice (>35):", bool_slice)
print("Fancy index slice:", index_slice)
print("\nRows 0 & 2:\n", rows_0_2)
print("Columns 1 & 3:\n", cols_1_3)
print("\nEvery 2nd column:\n", every_2_cols)
print("Every 2nd row:\n", every_2_rows)
print("\nMixed slicing:", mix_slice)



In [ ]:

# 3
# how to create an array of any shape filled only with zeros
# how to create an array of any shape filled only with ones
# how to create an array of any shape filled only with particular value
# how to create an identity matrix of any shape
# 4
# how to create an array with regularly spaced values between a start and end value
# how to create an array with a specified number of evenly spaced values between a start and end value

In [ ]:
a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.full((2,3),5)
print(c)
d = np.identity(2)
print(d)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.linspace(1,100,5)
print(e)
f = np.arange(1,100,5).shape()
print(f)

[  1.    25.75  50.5   75.25 100.  ]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


MORE ALGEBRAIC CODES

1. how to compute the dot product of two arrays
2. how to compute the inverse of a squeare matrix
3. how to calculate the eigenvalues and eigenvectors of a square matrix


In [ ]:
import numpy as np

# Sample arrays/matrices
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Sample square matrix
M = np.array([[4, 2],
              [3, 1]])

# 1. Compute the dot product of two arrays
dot_product = np.dot(a, b)

# 2. Compute the inverse of a square matrix
inverse_matrix = np.linalg.inv(M)

# 3. Calculate eigenvalues and eigenvectors of a square matrix
eigenvalues, eigenvectors = np.linalg.eig(M)

print("Dot Product:", dot_product)
print("\nInverse Matrix:\n", inverse_matrix)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


INTERVIEW CODING QUESTIONS
1. How to perform matrix multiplication
2. How to find the invert of a matrix
3. How to calculate the determinant of a matrix
4. how to flatten a multidimensional array
5. How to calculate eigenvalues and eigenvectors of a matrix in numpy
6. How to reverse an array in numpy
7. How to normalize an array
8. How to calculate the correlation coefficient
9. what is the use of np.cumsum() and np.cumprod() functions
10. code a function to compute the moving average of 1d array
11. numpy program to create a checkerboard of 8x8 matrix using title method
12. write a function to compute the convolution of two matrices in numpy
13. write a code to replace all elements greater than a threshold in numpy array with specific value


In [ ]:
# NumPy’s np.dot() function or the @ operator is used for both matrix multiplication and dot product.
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Matrix Multiplication
C = np.dot(A, B)
# The result is: [[ 58  64] [139 154]]

In [ ]:
# In NumPy, you can use the numpy.linalg.inv function to find the inverse of a matrix.
# Conditions:
#The matrix must be square, i.e., it should have an equal number of rows and columns.
#The matrix should be non-singular (have a non-zero determinant).
import numpy as np

# Define the matrix
A = np.array([[4, 7], [2, 6]])

# Compute the matrix inverse
A_inv = np.linalg.inv(A)
print(A_inv)

In [ ]:
#
import numpy as np

# Define the matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

In [ ]:

# Flattening a multidimensional array means converting it into
# a 1-D array while keeping all elements in order.
# NumPy provides two common methods for flattening:
# 1. .flatten() → returns a copy of the flattened array
# 2. .ravel()   → returns a flattened view (no extra memory) if possible
# Both produce a 1-D array.


import numpy as np
arr = np.array([[1, 2], [3, 4]])
# Using flatten()
flat_arr = arr.flatten()
# Using ravel()
flat_arr2 = arr.ravel()

print(flat_arr)
print(flat_arr2)


In [ ]:

# Eigenvalues & Eigenvectors:
# For a square matrix A, eigenvalues (λ) and eigenvectors (v)
# satisfy the equation:  A v = λ v
# NumPy provides: np.linalg.eig(matrix)
# - Returns eigenvalues as a 1-D array
# - Returns eigenvectors as columns of a 2-D array
# Requirements: Matrix must be square (n x n)

import numpy as np

A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


In [ ]:

# Reversing an array means reversing its order of elements.
# Methods:
# 1. Using slicing arr[::-1]
# 2. Using np.flip(arr)
# Works for 1-D and multidimensional arrays


import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Using slicing
rev1 = arr[::-1]
# Using NumPy flip
rev2 = np.flip(arr)

print(rev1)
print(rev2)


In [ ]:

# Normalization makes data scale-adjusted.
# Two common methods:
# 1. Min-Max Normalization:
#    x_norm = (x - x.min()) / (x.max() - x.min())
#    Resulting range → [0, 1]
# 2. Z-score Normalization (Standardization):
#    x_std = (x - mean) / std
#    Mean becomes 0, standard deviation becomes 1.


import numpy as np
arr = np.array([10, 20, 30, 40, 50])
# Min-Max Normalization
min_max_norm = (arr - arr.min()) / (arr.max() - arr.min())
# Z-score Normalization
z_score_norm = (arr - arr.mean()) / arr.std()

print("Min-Max Normalized:", min_max_norm)
print("Z-score Normalized:", z_score_norm)


In [ ]:

# Correlation coefficient measures the linear relationship
# between two variables.
# NumPy provides:
# np.corrcoef(x, y)
# Returns a 2x2 matrix:
# [ [1, corr_xy],
#   [corr_yx, 1] ]
# corr_xy is the correlation coefficient.


import numpy as np
x = np.array([10, 20, 30, 40, 50])
y = np.array([5, 25, 35, 45, 60])
corr_matrix = np.corrcoef(x, y)

print("Correlation Matrix:\n", corr_matrix)
print("Correlation Coefficient:", corr_matrix[0, 1])


In [ ]:

# np.cumsum()
# • Computes the CUMULATIVE SUM of array elements.
# • Each element in the result is the sum of all previous elements
#   including the current one.
# Example:
# arr = [1, 2, 3]
# np.cumsum(arr) → [1, 3, 6]


# np.cumprod()
# • Computes the CUMULATIVE PRODUCT of array elements.
# • Each element in the result is the product of all previous
#   elements including the current one.
# Example:
# arr = [1, 2, 3]
# np.cumprod(arr) → [1, 2, 6]


import numpy as np
arr = np.array([1, 2, 3, 4])
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))


In [ ]:

# Moving Average:
# Smooths data by averaging a sliding window over the array.

# Logic:
# • Use convolution with a window of ones: np.convolve()
# • Normalize by dividing by window size
#
# Example:
# arr = [1,2,3,4], window=2
# Moving average = [1.5, 2.5, 3.5]

# NOTE: Only NumPy is used.


import numpy as np

def moving_average(arr, window_size):
    # Create a window of equal weights (for averaging)
    window = np.ones(window_size) / window_size

    # Perform convolution (valid mode gives only full overlaps)
    ma = np.convolve(arr, window, mode='valid')
    return ma

arr = np.array([1, 2, 3, 4, 5, 6])
print(moving_average(arr, 3))


In [ ]:

# Goal: Create an 8x8 checkerboard matrix (0s and 1s).
#
# Checkerboard pattern:
#   [[0,1],
#    [1,0]]
#
# Logic:
# • Create a 2×2 block
# • Use np.tile(block, (4,4)) to repeat it 4 times in both directions


import numpy as np
# Basic 2x2 checkerboard pattern
block = np.array([[0, 1],
                  [1, 0]])

# Repeat pattern to 8x8
checkerboard = np.tile(block, (4, 4))

print(checkerboard)


In [ ]:

# 2D Convolution Logic:
# • Flip kernel both horizontally and vertically (as per convolution)
# • Slide kernel over input matrix
# • Multiply element-wise & sum
# • Output shape = (input_rows - k_rows + 1, input_cols - k_cols + 1)
#
# Restrictions:
# • Only NumPy allowed → must compute manually (no scipy)


import numpy as np
def matrix_convolution(A, K):
    # Flip kernel for convolution (true convolution, not cross-correlation)
    K = np.flipud(np.fliplr(K))

    rows_A, cols_A = A.shape
    rows_K, cols_K = K.shape

    # Output size
    out_rows = rows_A - rows_K + 1
    out_cols = cols_A - cols_K + 1

    # Prepare output matrix
    output = np.zeros((out_rows, out_cols))

    # Slide kernel across the matrix
    for i in range(out_rows):
        for j in range(out_cols):
            # Extract the region of A
            region = A[i:i+rows_K, j:j+cols_K]
            # Element-wise multiply + sum
            output[i, j] = np.sum(region * K)

    return output

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

K = np.array([[1, 0],
              [0, -1]])

print(matrix_convolution(A, K))


In [ ]:

# Replace values in NumPy array:
#
# Logic:
# • Use boolean masking:
#       mask = arr > threshold
# • Replace:
#       arr[mask] = new_value
#
# Boolean masks allow vectorized operations WITHOUT loops.


import numpy as np
arr = np.array([5, 12, 7, 20, 3, 15])
threshold = 10
replace_value = 0

# Replace all elements > threshold
arr[arr > threshold] = replace_value

print(arr)
